---
title: "p8105_mtp_sal2222"
author: "Stephen Lewandowski"
date: "October 26, 2018"
output: 
  github_document:
    toc: true
---


```{r setup, include = FALSE}

library(tidyverse)
library(readxl)
library(devtools)
library(patchwork) #devtools::install_github("thomasp85/patchwork")
library(wordcountaddin)
#devtools::install_github("benmarwick/wordcountaddin", type = "source", dependencies = TRUE)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

### Introduction



### Dataset

I will load and tidy the data.

```{r load_activity_data, message = FALSE}

activity <- read_csv(file = "./data/p8105_mtp_data.csv") %>%
  janitor::clean_names() %>% 
  gather(key = daily_min, value = activity, activity_1:activity_1440) %>% 
  mutate(daily_min = str_replace(daily_min, "activity_", ""),
         daily_min = as.numeric(daily_min),
         day = ordered(day, levels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", 
"Friday", "Saturday"))) %>% 
  arrange(week, day)

activity
```



### Activity over time




### Day of week effect


### Daily activity profiles


```{r word count}
wordcountaddin::text_stats("p8105_mtp_sal2222.Rmd")
```

